services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - ./docker/pg_admin_servers.json:/pgadmin4/servers.json
      - pg_admin_data:/var/lib/pgadmin


volumes:
  pg_data:
  pg_admin_data:
